In [0]:
import numpy as np

```
1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
```

In [0]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

```
2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
```

In [0]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [0]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [0]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [0]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [0]:
a.reshape(-1, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

```
3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
```

In [0]:
a.reshape((2, -1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [0]:
a.reshape((6, -1))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [0]:
a.reshape((3, -1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [0]:
a.reshape((-1, 4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [0]:
a.reshape((-1, 1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

```
4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
```

Ответ: нет, так как атрибут ndim такого массива равен 2, то есть это двумерный массив:

In [0]:
b = a.reshape(12, 1)
b.ndim

2

```
5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
```

In [0]:
a = np.random.randn(3, 4)
a

array([[ 0.34296647, -2.19693404, -1.55415869,  0.41448771],
       [ 1.25027197,  0.71480834, -0.9949975 ,  1.44879923],
       [ 0.20657759,  0.40757014,  0.24286408, -2.45749997]])

In [0]:
b = a.flatten()
b

array([ 0.34296647, -2.19693404, -1.55415869,  0.41448771,  1.25027197,
        0.71480834, -0.9949975 ,  1.44879923,  0.20657759,  0.40757014,
        0.24286408, -2.45749997])

In [0]:
b.ndim

1

In [0]:
a.size

12

In [0]:
b.size

12

In [0]:
a.size == b.size

True

```
6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?
```

In [0]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [0]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [0]:
a.shape

(10,)

In [0]:
b.shape

(1, 10)

In [0]:
a.ndim

1

In [0]:
b.ndim

2

```
7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
число строк которого больше 1 и на 1 меньше, чем число строк двумерного 
массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.
```

```
Ответ: при вертикальном соединении двумерных массивов получится двумерный массив v.
Возможны 4 варианта значений атрибута shape массива v (исходя из v.size, равного 10):
    1. 1 строка, 10 столбцов
    2. 10 строк, 1 столбец
    3. 2 строки, 5 столбцов
    4. 5 строк, 2 столбца
1 и 3 варианты не подходят, так как у массива а число строк больше 1, 
а у массива b число строк должно быть больше 2 (так у него число строк больше на единицу, чем у a).
При вертикальном их соединении должно получиться не менее 5 строк.
2 вариант не подходит, так как число строк, равное 10 получится, 
только если сложить два четных или два нечетных числа строк, что противоречит условию.
4 вариант подходит, так число 5 можно получить как 2 + 3.
Значит, в массиве a 2 строки, а в массиве b - 3.
Так как итоговый массив при вертикальном соединении должен иметь такое же количество столбцов,
что и исходные массивы, то число столбцов массивов a и b должно равняться 2.
```

In [0]:
a = np.zeros((2, 2))
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [0]:
b = np.ones((3, 2))
b

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

Соединим массивы a и b  с помощью функции numpy.vstack:

In [0]:
v = np.vstack((a, b))
v

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

Либо с помощью функции numpy.concatenate, примененной к нулевой оси (строковая ось):

In [0]:
v = np.concatenate((a, b), axis = 0)
v

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

```
8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?
```

In [0]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
A = a.reshape((4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [0]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [0]:
np.linalg.det(B)

0.0

```
9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.
```

In [0]:
np.random.seed(1)

In [0]:
c = np.random.randint(0, 16, 16)
c

array([ 5, 11, 12,  8, 15,  9, 11,  5, 15,  0,  0,  1, 12,  7, 13, 12])

In [0]:
C = c.reshape(4, 4)
C

array([[ 5, 11, 12,  8],
       [15,  9, 11,  5],
       [15,  0,  0,  1],
       [12,  7, 13, 12]])

In [0]:
D = B + C
D

array([[ 10,  25,  35,  40],
       [ 29,  59,  97, 127],
       [ 38,  86, 149, 213],
       [ 44, 129, 225, 314]])

In [0]:
np.linalg.det(D)

74829.999999999956

In [0]:
np.linalg.matrix_rank(D)

4

In [0]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.06597621,  0.0903381 ,  0.03407724, -0.0512495 ],
       [ 0.37569157, -0.28370974,  0.18735801, -0.06020313],
       [-0.30430309,  0.32086062, -0.27689429,  0.09681946],
       [ 0.07295202, -0.12601898,  0.11666444, -0.0342777 ]])

```
10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы.
С помощью функции numpy.where, используя матрицу D_inv в качестве маски,
а матрицы B и C - в качестве источников данных,
получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1,
должны быть равны соответствующему элементу матрицы B,
а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0,
должны быть равны соответствующему элементу матрицы C.
```

In [0]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[ 0.,  1.,  1.,  0.],
       [ 1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.]])

In [0]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [0]:
C

array([[ 5, 11, 12,  8],
       [15,  9, 11,  5],
       [15,  0,  0,  1],
       [12,  7, 13, 12]])

In [0]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,   8],
       [ 14,   9,  86,   5],
       [ 15,  86,   0, 212],
       [ 32,   7, 212,  12]])